services:

# Traefik Reverse Proxy
  traefik:
    image: traefik:3.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    networks:
      internal-net:
      OlympusConnect:
        aliases:
          - traefik-prompt-nexus
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-nexus-prompt-db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    networks:
      - internal-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    networks:
      - internal-net

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - internal-net
    depends_on:
      - db
      - redis
    environment:
      # Set the seed flag here
      - SEED_DB=True
    env_file:
      - ./backend/.env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=internal-net"
      # Catch ALL traffic sent to this domain, regardless of the path
      - "traefik.http.routers.nexus-be.rule=Host(`nexus-be.ritwikrajsingh.com`)"
      # Route it straight to Django's port 8000
      - "traefik.http.services.nexus-be.loadbalancer.server.port=8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - internal-net
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nexus-fe.rule=Host(`nexus-fe.ritwikrajsingh.com`)"
      - "traefik.http.services.nexus-fe.loadbalancer.server.port=4200"
      - "traefik.docker.network=internal-net"

volumes:
  postgres_data:

networks:
  internal-net:
    driver: bridge
  OlympusConnect:
    external: true